### ISSUE TITLE
history creation에 delay를 1~2초 정도 적용하면 좋을 것 같아요

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#25]
CSR하는 페이지인 경우 페이지 컨텐츠가 모두 그려지지 않아 title이 제대로 수집되지 않는 상황이 있습니다.
페이지 렌더링을 기다려주는 차원에서 1~2초 정도의 딜레이를 넣어주면 좋을 것 같습니다!

**Comment by BeomyeonAndrewKim** [comment]
@greatSumini  1.5초 뒤에 POST하는걸로 적용했어요~
crx 파일 슬랙에 공유드렸던 구글드라이브 링크에서 다시 다운로드 받아서 적용부탁드려요~

**Comment by greatSumini** [comment]
넵~!
