### ISSUE TITLE
YouTube 영상 시청 페이지가 수집되지 않습니다.

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#26]
1. 구독 페이지에서 진입
2. 새로고침
3. 주소 복사해서 새 탭에서 열기

다 시도해봐도 기록이 안 되네요 ㅠㅠ 왜일까요??

사용한 페이지 링크: https://www.youtube.com/watch?v=dDG1kKSQ88I

**Comment by greatSumini** [comment]
history stack? 영향 없이 내부 javascript 실행만으로 페이지가 전환된 경우 수집되지 않는 것 같습니다.
interval로 URL pathname 계속 검사하면서 바뀐 경우 새로운 history로 넘어가야할 것 같아요!!

**Comment by BeomyeonAndrewKim** [comment]
@greatSumini 아마 중간에 이벤트가 끊겼던 것 같아요. 의심되는 부분 일단 고쳐봤고
SPA에서 URL바뀌었을때랑, 유투브 영상 바꿀때 모두 적용되는 것까지 확인했어요.
이것도 마찬가지로 crx 다시 다운 받아서 테스트 부탁드려요~

**Comment by greatSumini** [comment]
@BeomyeonAndrewKim  넵 감사합니다!
