### ISSUE TITLE
favicon 수집되지 않은 경우, 없는 경우 대처하기

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#27]
![Screen Shot 2022-08-15 at 10 00 49 PM](https://user-images.githubusercontent.com/48555121/184639653-e1ff7801-856e-4269-831a-682056daf270.png)

현재 favicon이 없거나 불러오지 못한 경우 위처럼 UI가 표시됩니다.
아예 favicon이 없는 사이트도 있고, origin 보고 forbidden error 뱉는 곳들도 있어서 대응이 필요할 것 같아요 ㅠ

아래 링크 같은 방법을 도입해보면 좋을 것 같아유

https://blind513.tistory.com/605

**Comment by b41-41** [comment]
```
                  onError={({ currentTarget }) => {
                    currentTarget.onerror = null;
                    currentTarget.src = `주소`;
                  }}
```

**Comment by BeomyeonAndrewKim** [comment]
@b41-41 @greatSumini 고쳤어요~
저희 자체 로고나오면 그걸로 교체할 예정입니다
