### ISSUE TITLE
방문기록 리스트 주소 폰트 스타일 오류

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#28]
현재
![Screen Shot 2022-08-15 at 10 01 57 PM](https://user-images.githubusercontent.com/48555121/184639854-a3d19737-474b-4fc8-9255-e783c658099c.png)

피그마
![Screen Shot 2022-08-15 at 10 02 38 PM](https://user-images.githubusercontent.com/48555121/184639950-9f0c3530-521d-444d-8b8d-a33f74c2ed8d.png)

피그마와 폰트 색상 등이 다른 것 같습니다!

**Comment by BeomyeonAndrewKim** [comment]
@greatSumini  고쳤어요~
