### ISSUE TITLE
기간필터 오류

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#29]
![Screen Shot 2022-08-15 at 10 57 45 PM](https://user-images.githubusercontent.com/48555121/184649262-c7ebfcc6-6def-4a40-b8e1-1895ad0d9089.png)
![Screen Shot 2022-08-15 at 10 55 54 PM](https://user-images.githubusercontent.com/48555121/184648976-85f8edb5-46df-4583-be15-856548ac18bc.png)

시작일 2022-08-15, 종료일 2022-08-15 선택했을 때의 query parameter입니다. 보시다싶이 시작과 끝이 같습니다 ㅠ
아래처럼 변경돼야할 것 같아유

createdAtBetween[]=2022-08-14T15:00:00.000Z&createdAtBetween[]=2022-08-15T14:59:59.000Z

**Comment by BeomyeonAndrewKim** [comment]
고쳤습니다~
메인페이지는 바로 확인하시면되고
팝업은 익스텐션 파일 슬랙 링크에서 다시 다운받으셔서 재설치하고 확인해주시면 됩니다!
(분명 업데이트 같은게 있을 것 같은데.. 당분간은 일단 이렇게 확인해주세요)
