### ISSUE TITLE
active중이지 않은 tab 페이지의 체류시간이 증가하는 현상

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#34]
여러 페이지를 각기 다른 탭에 띄워놓은 경우, 비활성화된 탭들의 페이지도 체류시간이 계속 증가합니다 ㅠ

**Comment by BeomyeonAndrewKim** [comment]
@greatSumini  interval을 불필요하게 객체에 담아서 관리하다보니 clear하지 않는 경우가 종종 있었네요.
지금은 interval을 하나로 관리해서 처리했습니다. 아마 이젠 clear하지 못하는 경우는 없을 것 같아요

crx다시 받아서 확인부탁드려요~

**Comment by greatSumini** [comment]
@BeomyeonAndrewKim 감사합니다 ㅎㅎ
