### ISSUE TITLE
Extension ui의 achievement가 더미데이터인 것 같습니다.

### ISSUE THREAD

**Issue by greatSumini** [Nexters/websurfer-extension#37]
![Screen Shot 2022-08-18 at 7 09 18 PM](https://user-images.githubusercontent.com/48555121/185370548-e8aba25b-6bd4-421f-bcf4-a88c785fd046.png)

웹에 뜨는 것과 다르게 나옵니다!! 🥲

**Comment by BeomyeonAndrewKim** [comment]
@greatSumini 아 이거 어제 말씀드렸는데 ㅋㅋ 태그사진 완성되기전에  제출한거라서 안나와요
다시 제출할게여

**Comment by greatSumini** [comment]
@BeomyeonAndrewKim 앗 넵 ㅋㅋㅋ
